# Generated by Django 4.2.3 on 2023-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_client_country_client_age_client_card_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='physical_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='residence_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
