from django import forms
from .models import Inspection

class InspectionForm(forms.ModelForm):
    class Meta:
        model = Inspection
        fields = '__all__'
        widgets = {
            'date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Select date'}),
            'car': forms.Select(attrs={'class': 'form-control'}),
            'current_mileage': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter current mileage'}),
            'service_tag': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter service tag'}),
            'next_service_due': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Select next service due date'}),
            'insurance_expiry': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Select insurance expiry date'}),
            'fuel_tank_level': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter fuel tank level'}),
            'oil_level': forms.Select(attrs={'class': 'form-control'}),
            'brake_fluid': forms.Select(attrs={'class': 'form-control'}),
            'power_steering_fluid': forms.Select(attrs={'class': 'form-control'}),
            'clutch_fluid': forms.Select(attrs={'class': 'form-control'}),
            'auto_transmission_fluid': forms.Select(attrs={'class': 'form-control'}),
            'radiator_fluid_level': forms.Select(attrs={'class': 'form-control'}),
            'windshield_washer_level': forms.Select(attrs={'class': 'form-control'}),
            'voltage_recorded': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter voltage recorded'}),
            'terminals_checked_and_tightened': forms.Select(attrs={'class': 'form-control'}),
            'battery_fluid': forms.Select(attrs={'class': 'form-control'}),
            'headlights_working': forms.Select(attrs={'class': 'form-control'}),
            'high_beam_working': forms.Select(attrs={'class': 'form-control'}),
            'brake_lights_working': forms.Select(attrs={'class': 'form-control'}),
            'indicators_working': forms.Select(attrs={'class': 'form-control'}),
            'reverse_lights_working': forms.Select(attrs={'class': 'form-control'}),
            'fog_lights_working': forms.Select(attrs={'class': 'form-control'}),
            'fr_tire_brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter front right tire brand'}),
            'fr_tire_condition': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter front right tire condition'}),
            'fl_tire_brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter front left tire brand'}),
            'fl_tire_condition': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter front left tire condition'}),
            'rr_tire_brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter rear right tire brand'}),
            'rr_tire_condition': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter rear right tire condition'}),
            'rl_tire_brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter rear left tire brand'}),
            'rl_tire_condition': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter rear left tire condition'}),
            'spare_tire_brand': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter spare tire brand'}),
            'spare_tire_condition': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter spare tire condition'}),
            'warning_lights': forms.Select(attrs={'class': 'form-control'}),
            'air_conditioning_working': forms.Select(attrs={'class': 'form-control'}),
            'radio_working': forms.Select(attrs={'class': 'form-control'}),
            'CD': forms.Select(attrs={'class': 'form-control'}),
            'USB': forms.Select(attrs={'class': 'form-control'}),
            'AUX': forms.Select(attrs={'class': 'form-control'}),
            'FM_Expander': forms.Select(attrs={'class': 'form-control'}),
            'windscreen_condition': forms.Select(attrs={'class': 'form-control'}),
            'wipers_working': forms.Select(attrs={'class': 'form-control'}),
            'seat_belts_functioning': forms.Select(attrs={'class': 'form-control'}),
            'electric_mirrors_functioning': forms.Select(attrs={'class': 'form-control'}),
            'electric_windows_functioning': forms.Select(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter first name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter last name'}),
            'drivers_signature': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter driver\'s signature'}),
            'inspectors_first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter inspector\'s first name'}),
            'inspectors_last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter inspector\'s last name'}),
            'inspectors_signature': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter inspector\'s signature'}),
            'additional_comments': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter additional comments'}),
            'dashboard_image': forms.FileInput(attrs={'class': 'form-control'}),
            'car_damage_images': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }
