# Generated by Django 4.2.3 on 2023-07-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_remove_car_available_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmake'),
        ),
    ]
