# Generated by Django 4.2.3 on 2023-07-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_carmake_remove_car_name_carmodel_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmake'),
        ),
    ]
