# Generated by Django 4.2.3 on 2023-07-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_car_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carclass'),
        ),
    ]
