# Generated by Django 4.2.3 on 2023-07-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_carclass_car_car_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='weekly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
