# Generated by Django 4.2.3 on 2023-07-29 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_car_monthly_rate_car_weekly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
