# Generated by Django 4.2.3 on 2023-08-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_servicecompany_carservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
