# Generated by Django 4.2.3 on 2023-09-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_rename_description_carservice_service_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='next_service',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
