# Generated by Django 4.2.3 on 2023-09-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_alter_carservice_next_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='next_service',
            field=models.DateField(blank=True, null=True),
        ),
    ]
