# Generated by Django 4.2.6 on 2023-10-04 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0024_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='next_service',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
