# Generated by Django 4.2.6 on 2023-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0025_alter_carservice_next_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='next_service',
            field=models.DateTimeField(null=True),
        ),
    ]
