# Generated by Django 4.2.3 on 2023-07-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rates_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
