# Generated by Django 4.2.3 on 2023-07-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_days_reservation_rates_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
