# Generated by Django 4.2.3 on 2023-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_reservation_vat_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='add_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='use_custom_rates',
            field=models.BooleanField(default=False),
        ),
    ]
