# Generated by Django 4.2.3 on 2023-07-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_reservation_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='add_tax',
            new_name='add_VAT',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='use_custom_rates',
            new_name='apply_normal_rates',
        ),
    ]
