# Generated by Django 4.2.3 on 2023-07-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_rename_add_tax_reservation_add_vat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rates_applied',
            new_name='daily_rates',
        ),
    ]
