# Generated by Django 4.2.3 on 2023-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_rename_rates_applied_reservation_daily_rates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rate',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_amount_vat',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
