# Generated by Django 4.2.3 on 2023-07-31 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_rename_rate_reservation_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('car_class', models.CharField(max_length=100)),
                ('mileage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
