# Generated by Django 4.2.3 on 2023-08-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_carout_age_carout_card_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carout',
            name='physical_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carout',
            name='residence_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
