# Generated by Django 4.2.3 on 2023-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_carout_physical_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carout',
            name='number_plate',
            field=models.CharField(max_length=20),
        ),
    ]
