# Generated by Django 4.2.3 on 2023-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_carout_email_carout_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carout',
            name='where_the_car_will_be_used_or_parked',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
