# Generated by Django 4.2.3 on 2023-08-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_carout_amount_carout_deposit_carout_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('car_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.carout')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('car_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.carinspection')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.inspectionitem')),
            ],
        ),
        migrations.AddField(
            model_name='carinspection',
            name='inspection_items',
            field=models.ManyToManyField(through='reservations.InspectionItemStatus', to='reservations.inspectionitem'),
        ),
    ]
