# Generated by Django 4.2.3 on 2023-08-11 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_alter_carout_email_alter_carout_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='damages_noted',
        ),
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='fuel_in',
        ),
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='fuel_out',
        ),
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='kms_allowed',
        ),
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='kms_driven',
        ),
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='kms_in',
        ),
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='kms_out',
        ),
        migrations.AddField(
            model_name='carinspection',
            name='damages_noted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carinspection',
            name='fuel_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_in', to='reservations.fuel'),
        ),
        migrations.AddField(
            model_name='carinspection',
            name='fuel_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_out', to='reservations.fuel'),
        ),
        migrations.AddField(
            model_name='carinspection',
            name='kms_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carinspection',
            name='kms_driven',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carinspection',
            name='kms_in',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carinspection',
            name='kms_out',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
