# Generated by Django 4.2.3 on 2023-08-12 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_remove_carinspection_damages_noted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carout',
            name='damages_noted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='fuel_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_in_fuel', to='reservations.fuel'),
        ),
        migrations.AddField(
            model_name='carout',
            name='fuel_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_out_fuel', to='reservations.fuel'),
        ),
        migrations.AddField(
            model_name='carout',
            name='kms_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='kms_driven',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='kms_in',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='kms_out',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
