# Generated by Django 4.2.3 on 2023-08-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_carout_damages_noted_carout_fuel_in_carout_fuel_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carout',
            name='fuel_in',
            field=models.CharField(choices=[('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('Full', 'Full')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='carout',
            name='fuel_out',
            field=models.CharField(choices=[('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('Full', 'Full')], max_length=5, null=True),
        ),
    ]
