# Generated by Django 4.2.3 on 2023-08-12 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_alter_carout_fuel_in_alter_carout_fuel_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='carout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carout',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
