# Generated by Django 4.2.3 on 2023-08-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0031_carout_checked_in_carin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarIn',
        ),
    ]
