# Generated by Django 4.2.3 on 2023-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0032_delete_carin'),
    ]

    operations = [
        migrations.AddField(
            model_name='carout',
            name='check_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
