# Generated by Django 4.2.3 on 2023-08-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0033_carout_check_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carout',
            old_name='check_date_time',
            new_name='check_in_date_time',
        ),
    ]
