# Generated by Django 4.2.3 on 2023-08-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0034_rename_check_date_time_carout_check_in_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionitemstatus',
            name='checked_in',
        ),
    ]
