# Generated by Django 4.2.3 on 2023-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0039_carout_balance_carout_sub_total_carout_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carout',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
