# Generated by Django 4.2.3 on 2023-09-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0040_alter_carout_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='carout',
            name='approver',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
