# Generated by Django 4.2.3 on 2023-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0041_carout_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='carout',
            name='o_country_of_issue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='o_drivers_dl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='o_drivers_dl_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carout',
            name='o_drivers_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
