# Generated by Django 4.2.6 on 2023-10-04 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0045_reservation_contract_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='transaction_month',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 17, 47, 36, 429065, tzinfo=datetime.timezone.utc)),
        ),
    ]
