# Generated by Django 4.2.6 on 2023-10-04 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0046_income_transaction_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='income',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='transaction_month',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 18, 9, 12, 459201, tzinfo=datetime.timezone.utc)),
        ),
    ]
