# Generated by Django 4.2.6 on 2023-10-04 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0047_income_net_amount_income_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='standard_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='transaction_month',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 19, 56, 31, 182447, tzinfo=datetime.timezone.utc)),
        ),
    ]
