# Generated by Django 4.2.3 on 2023-12-01 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0048_reservation_standard_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='transaction_month',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 12, 38, 5, 431952, tzinfo=datetime.timezone.utc)),
        ),
    ]
