# Generated by Django 4.2.3 on 2024-01-11 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0059_alter_income_transaction_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='transaction_month',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 9, 1, 21, 31887, tzinfo=datetime.timezone.utc)),
        ),
    ]
