# Generated by Django 4.2.3 on 2024-01-12 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0063_alter_income_transaction_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='transaction_month',
            field=models.DateField(default=datetime.datetime(2024, 1, 12, 13, 1, 20, 731520, tzinfo=datetime.timezone.utc)),
        ),
    ]
