# Generated by Django 4.2.3 on 2024-02-13 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0064_alter_income_transaction_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='transaction_month',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 9, 32, 16, 137760, tzinfo=datetime.timezone.utc)),
        ),
    ]
