# Generated by Django 4.2.3 on 2023-12-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluidStatusChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'OK'), (2, 'Top Up'), (3, 'Check')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YesNoChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='AUX',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='CD',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='FM_Expander',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='USB',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='air_conditioning_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='auto_transmission_fluid',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='battery_fluid',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='brake_fluid',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='brake_lights_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='clutch_fluid',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='electric_mirrors_functioning',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='electric_windows_functioning',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='fog_lights_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='headlights_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='high_beam_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='indicators_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='oil_level',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='power_steering_fluid',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='radiator_fluid_level',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='radio_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='reverse_lights_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='seat_belts_functioning',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='terminals_checked_and_tightened',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='warning_lights',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='windscreen_condition',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='windshield_washer_level',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='wipers_working',
        ),
        migrations.AddField(
            model_name='inspection',
            name='AUX',
            field=models.ManyToManyField(related_name='AUX_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='CD',
            field=models.ManyToManyField(related_name='CD_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='FM_Expander',
            field=models.ManyToManyField(related_name='FM_Expander_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='USB',
            field=models.ManyToManyField(related_name='USB_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='air_conditioning_working',
            field=models.ManyToManyField(related_name='air_conditioning_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='auto_transmission_fluid',
            field=models.ManyToManyField(related_name='auto_transmission_fluid_inspections', to='inspection.fluidstatuschoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='battery_fluid',
            field=models.ManyToManyField(related_name='battery_fluid_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='brake_fluid',
            field=models.ManyToManyField(related_name='brake_fluid_inspections', to='inspection.fluidstatuschoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='brake_lights_working',
            field=models.ManyToManyField(related_name='brake_lights_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='clutch_fluid',
            field=models.ManyToManyField(related_name='clutch_fluid_inspections', to='inspection.fluidstatuschoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='electric_mirrors_functioning',
            field=models.ManyToManyField(related_name='electric_mirrors_functioning_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='electric_windows_functioning',
            field=models.ManyToManyField(related_name='electric_windows_functioning_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='fog_lights_working',
            field=models.ManyToManyField(related_name='fog_lights_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='headlights_working',
            field=models.ManyToManyField(related_name='headlights_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='high_beam_working',
            field=models.ManyToManyField(related_name='high_beam_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='indicators_working',
            field=models.ManyToManyField(related_name='indicators_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='oil_level',
            field=models.ManyToManyField(related_name='oil_level_inspections', to='inspection.fluidstatuschoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='power_steering_fluid',
            field=models.ManyToManyField(related_name='power_steering_fluid_inspections', to='inspection.fluidstatuschoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='radiator_fluid_level',
            field=models.ManyToManyField(related_name='radiator_fluid_level_inspections', to='inspection.fluidstatuschoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='radio_working',
            field=models.ManyToManyField(related_name='radio_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='reverse_lights_working',
            field=models.ManyToManyField(related_name='reverse_lights_working_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='seat_belts_functioning',
            field=models.ManyToManyField(related_name='seat_belts_functioning_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='terminals_checked_and_tightened',
            field=models.ManyToManyField(related_name='terminals_checked_and_tightened_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='warning_lights',
            field=models.ManyToManyField(related_name='warning_lights_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='windscreen_condition',
            field=models.ManyToManyField(related_name='windscreen_condition_inspections', to='inspection.yesnochoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='windshield_washer_level',
            field=models.ManyToManyField(related_name='windshield_washer_level_inspections', to='inspection.fluidstatuschoice'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='wipers_working',
            field=models.ManyToManyField(related_name='wipers_working_inspections', to='inspection.yesnochoice'),
        ),
    ]
