# Generated by Django 4.2.3 on 2023-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_remove_yesnochoice_value_yesnochoice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluidstatuschoice',
            name='value',
        ),
        migrations.AddField(
            model_name='fluidstatuschoice',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
