# Generated by Django 4.2.3 on 2023-12-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_remove_fluidstatuschoice_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='drivers_signature',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspectors_signature',
        ),
    ]
