# Generated by Django 4.2.3 on 2024-01-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_remove_inspection_car_damage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='car_damage_images',
        ),
        migrations.AddField(
            model_name='inspection',
            name='car_damage_images',
            field=models.ImageField(blank=True, null=True, upload_to='damage_images/'),
        ),
    ]
