# Generated by Django 4.2.3 on 2024-01-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_remove_inspection_car_damage_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='next_service_due',
            field=models.CharField(max_length=100),
        ),
    ]
