# Generated by Django 4.2.3 on 2024-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_alter_inspection_next_service_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='car_damage_images',
        ),
        migrations.AddField(
            model_name='inspection',
            name='car_damage_images',
            field=models.ManyToManyField(blank=True, related_name='damage_images_set', to='inspection.damageimage'),
        ),
    ]
